config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :jobs
  resources :applies

  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/job.rb
class Job < ApplicationRecord

    enum :status, [:error, :active, :ended]

    has_many :applies

    has_one_attached :image

    validates :title, presence: true
    validates :image, presence: true
    validates :description, presence: true

    def to_s
        self.title
    end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :current_user_admin

    def new
        @job = Job.new
    end

    def show
        @job = Job.find(params[:id])
        @applies = Apply.where(job_id: @job.id) 

    end

    def create
        @job = Job.new(jobs_params)
        respond_to do |format|
            if @job.save
                format.html { redirect_to root_path, notice: "La postulación ha sido realizada exitosamente." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end



    def update
        respond_to do |format|
            if @job.update(jobs_params)
              format.html { redirect_to root_path, notice: "La postulación ha sido modificada exitosamente." }
            else
              format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    private

    def set_job
        @job = Job.find(params[:id])
    end

    def jobs_params
        params.require(:job).permit(:title, :image, :description)
    end


end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> impidieron que este empleo se guardara:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Título", class: ["form-label"] %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :image, "Imagen", class: ["form-label"] %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción", style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit "Crear la Publicación de la Imagen", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="row py-5">
    <div class="col-12">
      <h1 class="text-center">Modifica el estado del trabajo</h1>
    </div>
</div>
  
 <div class="row py-5">
    <div class="col-12">
      <%= render "modify", jobs: @jobs %>
    </div>
 </div>
  
 <div class="row py-5">
    <div class="col-12">
      <%= link_to "Vuelve al inicio", root_path, class: "btn btn-primary w-100" %>
    </div>
</div>

app/views/jobs/new.html.erb
<div class="row py-5">
    <h2 class="text-center">Nueva vacante de trabajo</h2>
</div>

<div class="row py-5">
    <%= render "form", job: @job %>
</div>

<div class="row py-5">
    <%= link_to "Vuelve", root_path %>
</div>
  

app/views/jobs/show.html.erb
<div class="row py-5">
    <h2 class="text-center">Solicitudes</h2>
</div>

<div class="row py-5">
    <% @applies.each do |apply| %>
        <div class="col-12">
            <h4 class="text-center">Solicitud #<%= apply.id %></h4>
            <p>Trabajo: <%= @job.title %> </p>
            <p>Solicitante: <%= apply.user.name.to_s %></p>
            <p>Estado: <%= apply.status %></p>
            <p>Motivo para contratación: <%= apply.application %></p>
            <%= link_to 'Modificar el estado de la solicitud', edit_apply_path(apply.id), class: 'btn btn-primary w-100' %>
        </div>
    <% end %>
</div>

<div class="row py-5">
    <%= link_to "Volver", root_path %>
</div>